# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(537, 304)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 320, 280))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.gridLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(3)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_fio = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_fio.setObjectName("lineEdit_fio")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_fio)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_date = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_date.setObjectName("lineEdit_date")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_date)
        self.btnSetDate = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSetDate.setObjectName("btnSetDate")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btnSetDate)
        self.textBrowser = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.textBrowser)
        self.btnCreateDoc = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnCreateDoc.setObjectName("btnCreateDoc")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.btnCreateDoc)
        self.btnClear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnClear.setObjectName("btnClear")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.btnClear)
        self.lineEdit_sum_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_sum_2.setObjectName("lineEdit_sum_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_sum_2)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_sum = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_sum.setObjectName("lineEdit_sum")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_sum)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 10, 181, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(340, 30, 191, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(340, 60, 191, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(340, 80, 221, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(340, 240, 211, 21))
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ФИО"))
        self.label_2.setText(_translate("MainWindow", "Период"))
        self.btnSetDate.setText(_translate("MainWindow", "Добавить"))
        self.btnCreateDoc.setText(_translate("MainWindow", "Создать документ"))
        self.btnClear.setText(_translate("MainWindow", "Очистить"))
        self.label_4.setText(_translate("MainWindow", "Имя файла"))
        self.label_3.setText(_translate("MainWindow", "Размер пособия"))
        self.label_5.setText(_translate("MainWindow", "ФИО - в дательном падеже (кому?)"))
        self.label_6.setText(_translate("MainWindow", "Дробную часть указывать через \'.\'"))
        self.label_7.setText(_translate("MainWindow", "Периоды через  \'—\' без пробелов"))
        self.label_8.setText(_translate("MainWindow", "Пример: 13.05.2020—19.05.2020"))
        self.label_9.setText(_translate("MainWindow", "Создастся в папке с файлом запуска"))
